version: "3.7"
services:
  app:
    build:
      args:
        user: abdo
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: personality
    container_name: personality-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - personality

  db:
    image: mysql:5.7
    container_name: personality-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: personality
      MYSQL_ROOT_PASSWORD: 'personality123'
      MYSQL_PASSWORD: 'personality123'
      MYSQL_USER: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - personality

  nginx:
    image: nginx:alpine
    container_name: personality-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - personality

networks:
  personality:
    driver: bridge
